name: CI-CD
on:
  push:
    branches:
      - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v6

      - name: view the files
        run: ls
